name: intern_intelligence_social_media_application
description: "Social Media Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #  Default Package
  get_it: ^8.0.3
  logger: ^2.6.1
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  failure_handler:
    git:
      url: https://github.com/SaifAllahGharib/failure_handler.git
      ref: master
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.7.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cached_network_image: ^3.4.1
  video_player: ^2.10.0
  photo_manager: ^3.7.1
  permission_handler: ^12.0.1
  mime: ^2.0.0
  path: ^1.9.1
  loading_animation_widget: ^1.3.0
  injectable: ^2.5.1
  firebase_database: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  injectable_generator: ^2.8.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true